import { Component } from "@angular/core";

@Component({
    selector: "app-customer-list",
    templateUrl: "./customer-list.component.html",
    styleUrl: "./customer-list.component.css",
})
export class CustomerListComponent {
    headers = [
        { name: "Customer No.", minWidth: "110px" },
        { name: "Customer Legal Name", minWidth: "190px" },
        { name: "Customer Trade Name", minWidth: "190px" },
        { name: "Country", minWidth: "110px" },
        { name: "State", minWidth: "110px" },
        { name: "City", minWidth: "110px" },
        { name: "Billing Address", minWidth: "190px" },
        { name: "Billing Email", minWidth: "190px" },
        { name: "Billing Contact Position", minWidth: "190px" },
        { name: "Billing Phone", minWidth: "190px" },
        { name: "Shipping Address", minWidth: "190px" },
        { name: "Shipping Email", minWidth: "190px" },
        { name: "Shipping Phone", minWidth: "190px" },
        { name: "Position", minWidth: "190px" },
    ];

    rows = [
        {
            customer_no: "C0201",
            customer_legal_name: "Heritage Bakery Ltd.",
            customer_trade_name: "Heritage Bakery",
            country: "CANADA",
            state: "Alberta",
            city: "Edmonton",
            billing_address: "862 Parsons Road",
            billing_email: "test201@demo.com",
            billing_contact_position: "Mary Collins Manager",
            billing_phone: "+1 780 000 0001",
            shipping_address: "862 Parsons Road SW, E",
            shipping_email: "test201@demo.co",
            shipping_phone: "+1 780 000 0001",
            position: "John Collins Manager",
        },
        {
            customer_no: "C0202",
            customer_legal_name: "Sunnyhill Supermarkets Ltd.",
            customer_trade_name: "Sunnyhill Supermarkets",
            country: "CANADA",
            state: "Ontario",
            city: "Scarborough",
            billing_address: "1900 Eglinton Ave",
            billing_email: "test202@demo.com",
            billing_contact_position: "Kim Lee Manager",
            billing_phone: "+1 780 000 0002",
            shipping_address: "1900 Eglinton Ave E, Sca",
            shipping_email: "test202@demo.co",
            shipping_phone: "+1 780 000 0002",
            position: "Frank Green Manager",
        },
        {
            customer_no: "C0203",
            customer_legal_name: "Greenhill Foods",
            customer_trade_name: "Greenhill Foods",
            country: "USA",
            state: "Texas",
            city: "Dallas",
            billing_address: "5665 E Mockingbird Lane",
            billing_email: "test203@demo.com",
            billing_contact_position: "Katherine Gibbs Manager",
            billing_phone: "+1 780 000 0003",
            shipping_address: "5665 E Mockingbird Lane",
            shipping_email: "test203@demo.co",
            shipping_phone: "+1 780 000 0003",
            position: "Brad Brown Manager",
        },
        {
            customer_no: "C0204",
            customer_legal_name: "St. Catherine Bakery",
            customer_trade_name: "Saint Catherine Classic Bakery",
            country: "CANADA",
            state: "Quebec",
            city: "Montreal",
            billing_address: "93 Saint-Catherine Street",
            billing_email: "test204@demo.com",
            billing_contact_position: "Marie Duval Manager",
            billing_phone: "+1 780 000 0004",
            shipping_address: "93 Saint-Catherine Street",
            shipping_email: "test204@demo.co",
            shipping_phone: "+1 780 000 0004",
            position: "Alexander Duval Manager",
        },
    ];

    keys = [
        { name: "customer_no" },
        { name: "customer_legal_name" },
        { name: "customer_trade_name" },
        { name: "country" },
        { name: "state" },
        { name: "city" },
        { name: "billing_address" },
        { name: "billing_email" },
        { name: "billing_contact_position" },
        { name: "billing_phone" },
        { name: "shipping_address" },
        { name: "shipping_email" },
        { name: "shipping_phone" },
        { name: "position" },
    ];
}
